// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class replace_ConsignmentType_with_DeliveryMethod_everywhere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replace_ConsignmentType_with_DeliveryMethod_everywhere));
        
        string IMigrationMetadata.Id
        {
            get { return "202009241435358_replace_ConsignmentType_with_DeliveryMethod_everywhere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
