// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class sortorderolumnaddedinproductarrtibutes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sortorderolumnaddedinproductarrtibutes));
        
        string IMigrationMetadata.Id
        {
            get { return "202007111214279_sortorderolumn-added-in-productarrtibutes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
