// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class removingprestashhopidfromproductmaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removingprestashhopidfromproductmaster));
        
        string IMigrationMetadata.Id
        {
            get { return "202001040114226_removing-prestashhopid-from-productmaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
