// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class PriceIncludingTaxadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceIncludingTaxadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202007090916421_Price-Including-Tax-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
