// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class loyaltyfieldsinaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loyaltyfieldsinaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202008071924483_loyalty-fields-in-account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
