// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SiteIDaddedinProductAllownceAndGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SiteIDaddedinProductAllownceAndGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "202005060313186_SiteID-added-in-ProductAllownceAndGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
