// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class shipmentaddressnameaddedinorderstables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shipmentaddressnameaddedinorderstables));
        
        string IMigrationMetadata.Id
        {
            get { return "202012162338233_shipment-address-name-added-in-orders-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
