// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mandatorylocationscanflagintenantconfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mandatorylocationscanflagintenantconfig));
        
        string IMigrationMetadata.Id
        {
            get { return "202008301541450_mandatory-location-scan-flag-in-tenant-config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
