// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dpdResonsecoulmnaddedindatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dpdResonsecoulmnaddedindatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202002280651064_dpdResonsecoulmn-added-in-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
