// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedsomeLoyaltyAppconfigstoTenantConfigstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsomeLoyaltyAppconfigstoTenantConfigstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202011091020383_added-some-LoyaltyApp-configs-to-TenantConfigs-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
