// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_sort_order_to_ProductManufacturers_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_sort_order_to_ProductManufacturers_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202008261303239_added_sort_order_to_ProductManufacturers_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
