// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MerakiPropertiesAddedInAssetLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MerakiPropertiesAddedInAssetLog));
        
        string IMigrationMetadata.Id
        {
            get { return "202002101310559_Meraki-Properties-Added-In-AssetLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
