// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedIsAutoShipmentfieldtoProductMastertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedIsAutoShipmentfieldtoProductMastertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202010070815394_added-IsAutoShipment-field-to-ProductMaster-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
