// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class setuseridnullableinCartitems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setuseridnullableinCartitems));
        
        string IMigrationMetadata.Id
        {
            get { return "202007021028069_setuserid-nullable-inCartitems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
