// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SmallLogoinTenantWebsitesandnominalcodechanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SmallLogoinTenantWebsitesandnominalcodechanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202009011907355_SmallLogo-in-TenantWebsites-and-nominal-code-changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
