// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedIsCollectionAvailableandIsDeliveryAvailablefieldstotenantwebsite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedIsCollectionAvailableandIsDeliveryAvailablefieldstotenantwebsite));
        
        string IMigrationMetadata.Id
        {
            get { return "202007100945322_added-IsCollectionAvailable-and-IsDeliveryAvailable-fields-to-tenant-website"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
