// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class producttypeaddedinProductmaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(producttypeaddedinProductmaster));
        
        string IMigrationMetadata.Id
        {
            get { return "202005232307351_producttype-added-inProductmaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
