// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addressline4droppedfromPTenantsPLandlordsandtenantlocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addressline4droppedfromPTenantsPLandlordsandtenantlocations));
        
        string IMigrationMetadata.Id
        {
            get { return "202011200721511_address-line-4-dropped-from-PTenants-PLandlords-and-tenant-locations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
