// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class showpricesincludingtaxaddedtenantwebsites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(showpricesincludingtaxaddedtenantwebsites));
        
        string IMigrationMetadata.Id
        {
            get { return "202007090129510_showpricesincluding-tax-added-tenantwebsites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
