// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedcountriesforTenantDeliveryServiceandPrestashopCountryIdremovedfromGlobalCountrytable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcountriesforTenantDeliveryServiceandPrestashopCountryIdremovedfromGlobalCountrytable));
        
        string IMigrationMetadata.Id
        {
            get { return "202012140148047_added-countries-for-TenantDeliveryService-and-PrestashopCountryId-removed-from-GlobalCountry-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
