// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ModilesTableDeletedplusdeliverycollectionpricelistsaddedintenantlocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModilesTableDeletedplusdeliverycollectionpricelistsaddedintenantlocations));
        
        string IMigrationMetadata.Id
        {
            get { return "202007262322244_Modiles-Table-Deleted-plus-delivery-collection-price-lists-added-in-tenant-locations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
