// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addressline4changedintoTown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addressline4changedintoTown));
        
        string IMigrationMetadata.Id
        {
            get { return "202010021724490_address-line-4-changed-into-Town"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
