// <auto-generated />
namespace Ganedata.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addcolorfieldtoattributestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolorfieldtoattributestable));
        
        string IMigrationMetadata.Id
        {
            get { return "202007111736215_add-color-field-to-attributes-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
